name: 'ClickUp Issue Integration for Polifemo'
description: 'Automates the creation of ClickUp tasks from GitHub issues for the Polifemo project'
author: 'Tommaso Morganti'

inputs:
  clickup_api_key:
    description: 'ClickUp API key'
    required: true

  problem_foledr_id:
    description: 'ClickUp folder ID for the problem issues'
    required: true

  feature_folder_id:
    description: 'ClickUp folder ID for the feature issues'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
